<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>e_store_maintanance_data_access</RootNamespace>
    <ImplicitUsings>disaple</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\e-store-maintanance-model\e-store-maintanance-model.csproj" />
  </ItemGroup>

</Project>
